Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        prenom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        mail:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        mdp:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
